baseURL = "https://kridk999.github.io/CSS_website_project_09/"
title = "Project Title"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Henrik Nielsen", "Inga Jensen", "Jacob"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/kridk999/CSS_website_project_09.git"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"